# Generated by Django 3.2.23 on 2023-11-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspelers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='club',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='voetbalspelers',
            name='name',
        ),
    ]
