# Generated by Django 3.2.23 on 2023-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231111_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspelers',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='voetbalspelers',
            name='club',
            field=models.TextField(null=True),
        ),
    ]
